- name: nginx install and run
  hosts: Target
  tasks:
  - name: nginx install
    ansible.builtin.package:
     name: nginx
     state: present
  - name: start nginx
    ansible.buildin.service:
     name: nginx
     state: started
     enabled: yes

