- name: nginx install and run
  hosts:
  tasks:
  - name: nginx install
    ansible.builtin.package:
    - name: nginx
      state: present
  - name: start nginx
    sansible.buildin.service:
    - name: nginx
      state: started
      enabled: yes

      