- name: Variables from args
  hosts: local
  connection: local
  tasks:
  - name: printing course information
    ansible.builtin.debug:
     msg: "hello i am learning {{ COURSE }} Duration {{ DURATION }} Trainer {{ TRAINER }}"