- name: Variable Preferences
  hosts: local
  connection: local
#  vars:
 #  GREETING: "Hello from play"
  #vars_files:
  #- Greetings.txt
  #vars_prompt:
  #- name: GREETING
   # prompt: Enter your Greetings
   # private: false
  tasks:
  - name: Print the Greetings
    #vars:
     #GREETING: "Hello from task"
    ansible.builtin.debug:
     msg: "{{ GREETING }}"
    
     


