- name: conditions demo
  hosts: local
  connection: local
  vars_prompt:
  - name: Number
    prompt: Please enter any number
    private: false
  tasks:
  - name: Print if number is lessthan or equal to 100
    when: Number | int <= 100
    ansible.builtin.debug:
     msg: "Given number {{ Number }} is lessthan or equal to 100"

  - name: Print if number is graterthan 100
    when: Number | int > 100
    ansible.builtin.debug:
     msg: "Given number {{ Number }} is graterthan 100"
