- name: conditions demo
  hosts: local
  connection: local
  vars:
  - Number: 67
  tasks:
  - name: Print if number is lessthan or equal to 100
    when: Number < 100
    ansible.builtin.debug:
     msg: "Given number {{ Number }} is lessthan or equal to 100"

  - name: Print if number is graterthan 100
    when: Number > 100
    ansible.builtin.debug:
     msg: "Given number {{ Number }} is graterthan 100"
