- name: Datatypes in Ansible
  hosts: local
  connection: local
  vars:
   DURATION: 100               # Number variable
   COURSE: "AWS with DevOps"   # String
   IS_LIVE: true               # Boolean
   TOOLS:                      # List []
   - Linux
   - Git
   - Ansible
   CONCEPTS:                   # Dictionary or map or object, reffred as { }
    CI: "Jenkins, Circle-CI"
    Scripting: "Linux, Ansible, Python"
  tasks:
  - name: Printing course information
    ansible.builtin.debug:
     msg: "Course is {{ COURSE }} Dutation {{ DURATION }}HR, is live? {{ IS_LIVE }} tools {{ TOOLS }} Conecpts {{ CONCEPTS }}"

