- name: Datatypes in Ansible
  hosts: local
  connection: local
  vars:
   DURATION: 100
   COURSE: "AWS with DevOps"
   IS_LIVE: true
   TOOLS:
   - Linux
   - Git
   - Ansible
   CONCEPTS: 
    CI: "Jenkins CIRCLE-CI"
    Scripting: "Linux,Ansible,Python"
  tasks:
  - name: Printing course information
    ansible.builtin.debug:
     msg: "Course is {{ COURSE }} Dutation {{ DURATION }}HR, is live? {{ IS_LIVE }} tools {{ TOOLS }} Conecpts {{ CONCEPTS }}"

