- name: Installing nginx based on OS Family"
  hosts: Target
  become: true
  tasks:
  - name : Installing nginx on RedHat OS
    when: "OS_family == RedHat"
    ansible.builtin.dnf:
    - name: nginx
      state: installed
  - name: Installing nginx on Debian OS
    when: "OS_family==Debian"
    ansible.builtin.apt:
    - name: nginx
      state: installed
