- name: Printing list of names using loops
  hosts: local
  connection: local
  tasks:
  - name: Printing names
    ansible.builtin.debug:
     msg: Hello "{{ item }}"
    loop:
     - Ramesh
     - Suresh
     - Raheem
  
