- name: Installing list of packages using loops
  hosts: Target
  become: true
  tasks:
  - name: Install list of packages
    ansible.builtin.package:
      name: "{{ items }}"
      state: present
    loop:
    - nginx
    - mysql
    - zip
       
   


