- name: functions
  hosts: local
  connection: local
  vars:
   persons: "Ramesh,Suresh,Mahesh"
  tasks:
  - name: converting to upper case
    ansible.builtin.debug:
     msg: Hello  "{{ persons }} | upper "

  