- name: functions
  hosts: local
  connection: local
  vars:
   person: "Ramesh,suresh,mahesh"
  tasks:
  - name: print name
    ansible.builtin.debug:
     msg: "{{ person | default('Ajay') }}"

  - name: printing names in list format
    ansible.builtin.debug:
     msg: Hello "{{ person | split(',') }}"

  - name: conver map to list
    vars:
     information:
      Name: Ajay
      Age: 27
      Gender: Male
    ansible.builtin.debug:
     msg: Info "{{ information | dict2items }}"
 

  