- name: functions
  hosts: local
  connection: local
  vars:
   person: "Ramesh,suresh,mahesh"
  tasks:
  - name: print name
    ansible.builtin.debug:
     msg: "{{ person | default('Ajay') }}"

  - name: printing names in list format
    ansible.builtin.debug:
     msg: Hello "{{ person | split(',') }}"
 

  