- name: shell and command moudule 
  hosts: Target
  tasks:
  - name: command mudule
    ansible.builtin.command: "ls -ltr"
    register: command_result
  - name: shell moudule
    ansible.builtin.shell: "echo Hello > /tmp/output.txt"
    register: shell_result
  - name: Printing result
    ansible.builtin.debug:
     msg: "{{ command_result shell_result }}"
     

