- name: "roboshop user creation"
  hosts: Frontend
  become: true
  tasks:
  - name: check user already exits or not
    ansible.builtin.command: id roboshop
    register: result
    ignore_error: true

  - name: creating user
    ansible.builtin.command: useradd roboshop
    when: result.rc != 0

  - name: user already exists
    ansible.builtin.debug:
     msg: "user already exists"
    when: result.rc == 0

